export {
  ParamTypeSchema,
  ParamScaleSchema,
  ParamMetadataSchema,
  SampleMetadataSchema,
  SynthSummarySchema,
  SynthMetadataSchema,
  ListSynthsResponseSchema,
  ProgramManifestSchema,
  ProgramSummarySchema,
  ListProgramsResponseSchema,
  CompositionResponseSchema,
  CompositionResponseSchema as CompositionSchema,
  CreateCompositionRequestSchema,
  CreateCompositionResponseSchema,
  GenerateRequestSchema,
  GenerateResponseSchema,
  DiscoverQuerySchema,
  DiscoverCompositionSchema,
  DiscoverResponseSchema,
  ErrorResponseSchema,
  ValidationErrorResponseSchema,
  StreamEventSchema,
} from "./generated/api-schemas.js";
